use_frameworks!

target 'MyFirstTestLibrary_Example' do
  pod 'MyFirstTestLibrary', :path => '../'

  target 'MyFirstTestLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'ASIHTTPRequest'
  pod 'MBProgressHUD'

  end
end
